package common

const (
	UTXOCoinType    = "UTXO"
	EvmCoinTye      = "EVM"
	EcdsaCoinType   = "ECDSA"
	Ed25519CoinType = "ED25519"
	StarkCoinType   = "STARK"

	TrxCoinType  = "TRX"
	BethCoinType = "BETH"
	AlgoCoinType = "ALGO"
	EOSCoinType  = "EOS"

	BtcMessageSignatureHeader  = "Bitcoin Signed Message:\n"
	LtcMessageSignatureHeader  = "Litecoin Signed Message:\n"
	DogeMessageSignatureHeader = "Dogecoin Signed Message:\n"
	DashMessageSignatureHeader = "DarkCoin Signed Message:\n"
	BtgMessageSignatureHeader  = "Bitcoin Gold Signed Message:\n"
	BcdMessageSignatureHeader  = "Bitcoindiamond Signed Message:\n"
	DgbMessageSignatureHeader  = "DigiByte Signed Message:\n"
	QtumMessageSignatureHeader = "Qtum Signed Message:\n"
	RvnMessageSignatureHeader  = "Raven Signed Message:\n"
	ZecMessageSignatureHeader  = "Zcash Signed Message:\n"

	EthMessageSignatureHeader    = "\x19Ethereum Signed Message:\n32"
	TronMessageSignatureHeader   = "\x19TRON Signed Message:\n32"
	TronMessageV2SignatureHeader = "\x19TRON Signed Message:\n"

	OKXMessageSignatureHeader = "OKX Signed Message:\n"
)

var (
	PorCoinAddressTypeMap = map[string]string{
		// UTXO
		"BTC":       "BTC",
		"USDT-OMNI": "BTC",
		"BCHN":      "BCH",
		"BCHA":      "BCHA",
		"BCH":       "BCH",
		"BSV":       "BTC",
		"LTC":       "LTC",
		"DOGE":      "DOGE",
		"DASH":      "DASH",
		"BTG":       "BTG",
		"BCD":       "BTC",
		"DGB":       "DGB",
		"QTUM":      "QTUM",
		"RVN":       "RVN",
		"ZEC":       "ZEC",

		// ETH
		"ETH":                  "ETH",
		"ETH-ARBITRUM":         "ETH",
		"ETH-OPTIMISM":         "ETH",
		"USDT-ERC20":           "ETH",
		"USDT-POLY":            "ETH",
		"USDT-AVAXC":           "ETH",
		"USDT-ARBITRUM":        "ETH",
		"USDT-OPTIMISM":        "ETH",
		"USDT-OKC20":           "ETH",
		"USDC":                 "ETH",
		"POLY-USDC":            "ETH",
		"USDC-AVAXC":           "ETH",
		"USDC-ARBITRUM":        "ETH",
		"USDC-OPTIMISM":        "ETH",
		"ETC":                  "ETH",
		"OKB-OKC20":            "ETH",
		"LTCK-OKC20":           "ETH",
		"FILK-OKC20":           "ETH",
		"USDC-OKC20":           "ETH",
		"SHIBK-KIP20":          "ETH",
		"DOTK-OKC20":           "ETH",
		"ETCK-KIP20":           "ETH",
		"XRPK-KIP20":           "ETH",
		"UNIK-OKC20":           "ETH",
		"BCHK-KIP20":           "ETH",
		"BABYDOGE-KIP20":       "ETH",
		"LINKK-OKC20":          "ETH",
		"TRXK-KIP20":           "ETH",
		"BABYDOGE-BSC":         "ETH",
		"SHIB":                 "ETH",
		"UNI":                  "ETH",
		"LINK":                 "ETH",
		"ETHW":                 "ETH",
		"BLUR":                 "ETH",
		"MATIC":                "ETH",
		"PEOPLE":               "ETH",
		"OKT":                  "ETH",
		"OKC":                  "ETH",
		"OKB":                  "ETH",
		"OPTIMISM":             "ETH",
		"ETH-LINEA":            "ETH",
		"BASE":                 "ETH",
		"OKB-X1":               "ETH",
		"OKB-X1-ETH":           "ETH",
		"OKB-X1-USDT":          "ETH",
		"OKB-X1-USDC":          "ETH",
		"POLY-USDC-3359":       "ETH",
		"USDC-OPTIMISM-FF85":   "ETH",
		"USDC-ARBITRUM-NATIVE": "ETH",
		"USDC-BASE":            "ETH",
		"ZKSYNC2":              "ETH",
		"ETHK-OKC20":           "ETH",
		"CORE":                 "ETH",
		"BERA":                 "ETH",
		"POLYGON":              "ETH",
		"ARBITRUM":             "ETH",
		"XLAYER":               "ETH",
		"AVAXC":                "ETH",
		"UNICHAIN":             "ETH",
		"CFX_EVM":              "ETH",
		"BSC":                  "ETH",
		"STORY":                "ETH",
		"ETH_LINEA":            "ETH",
		"MERLIN_BTC":           "ETH",
		"CHZ":                  "ETH",
		"RONIN":                "ETH",
		"KAIA":                 "ETH",
		"ACE":                  "ETH",
		"MOONBEAM":             "ETH",
		"METIS":                "ETH",
		"FLR":                  "ETH",
		"MOVR":                 "ETH",
		"SCROLL":               "ETH",
		"THETA":                "ETH",
		"SONIC":                "ETH",
		"LSK":                  "ETH",
		"CELO":                 "ETH",
		"G":                    "ETH",
		"SOPHON":               "ETH",
		"MERLIN":               "ETH",
		"OASYS":                "ETH",
		"ZETA":                 "ETH",

		// BETH
		"BETH": "BETH",

		// TRX
		"USDT-TRC20": "TRX",
		"USDC-TRC":   "TRX",
		"TRX":        "TRX",
		"TRON":       "TRX",

		// ECDSA
		"FIL":  "FIL",
		"CFX":  "CFX",
		"ELF":  "ELF",
		"LUNC": "LUNC",

		// ED25519
		"SOL":         "SOL",
		"USDC-SPL":    "SOL",
		"USDT-SPL":    "SOL",
		"APTOS":       "APTOS",
		"APTOS-FA":    "APTOS",
		"USDT-APTOS":  "APTOS",
		"USDC-APTOS":  "APTOS",
		"APT":         "APTOS",
		"SUI":         "SUI",
		"USDC-SUI":    "SUI",
		"TONCOIN-NEW": "TON",
		"USDT-TON":    "TON",
		"TON":         "TON",
		"DOT":         "DOT",

		// ALGO
		"USDT-ALGO": "ALGO",

		// FEVM
		"FIL-EVM": "FIL",
		"FEVM":    "FIL",

		"XLM":     "XLM",
		"PI":      "PI",
		"STELLAR": "STELLAR",
		"ADA":     "ADA",
		"NEAR":    "NEAR",
		"HBAR":    "HBAR",
		"HEDERA":  "HBAR",
		"SC":      "SC",
		"IOTA":    "IOTA",
		"ICP":     "ICP",
		"ACA":     "ACA",
		"CSPR":    "CSPR",
		"KSM":     "KSM",
		"TEZOS":   "TEZOS",
		"KDA":     "KDA",
		"EGLD":    "EGLD",
		"ENJ":     "ENJ",
		"ALGO":    "ALGO",
		"STX":     "STX",
		"ASTR":    "ASTR",
		"TIA":     "TIA",
		"ATOM":    "ATOM",
		"CRO":     "CRO",
		"DORA":    "DORA",
		"DYDX":    "DYDX",
		"INJ":     "INJ",
		"TERRA":   "TERRA",
		"IOST":    "IOST",
		"ICX":     "ICX",
		"LAT":     "LAT",
		"ONE":     "ONE",
		"FLOW":    "FLOW",

		// EOS
		"EOS": "EOS",
		"A":   "EOS",
	}

	PorCoinTypeMap = map[string]string{
		// UTXO
		"BTC":       UTXOCoinType,
		"USDT-OMNI": UTXOCoinType,
		"BCHN":      UTXOCoinType,
		"BCHA":      UTXOCoinType,
		"BCH":       UTXOCoinType,
		"BSV":       UTXOCoinType,
		"LTC":       UTXOCoinType,
		"DOGE":      UTXOCoinType,
		"DASH":      UTXOCoinType,
		"BTG":       UTXOCoinType,
		"BCD":       UTXOCoinType,
		"DGB":       UTXOCoinType,
		"QTUM":      UTXOCoinType,
		"RVN":       UTXOCoinType,
		"ZEC":       UTXOCoinType,

		// ETH
		"ETH":                  EvmCoinTye,
		"ETH-ARBITRUM":         EvmCoinTye,
		"ETH-OPTIMISM":         EvmCoinTye,
		"USDT-ERC20":           EvmCoinTye,
		"USDT-POLY":            EvmCoinTye,
		"USDT-AVAXC":           EvmCoinTye,
		"USDT-ARBITRUM":        EvmCoinTye,
		"USDT-OPTIMISM":        EvmCoinTye,
		"USDC":                 EvmCoinTye,
		"POLY-USDC":            EvmCoinTye,
		"USDC-AVAXC":           EvmCoinTye,
		"USDC-ARBITRUM":        EvmCoinTye,
		"USDC-OPTIMISM":        EvmCoinTye,
		"ETC":                  EvmCoinTye,
		"BABYDOGE-BSC":         EvmCoinTye,
		"SHIB":                 EvmCoinTye,
		"UNI":                  EvmCoinTye,
		"LINK":                 EvmCoinTye,
		"ETHW":                 EvmCoinTye,
		"BLUR":                 EvmCoinTye,
		"MATIC":                EvmCoinTye,
		"PEOPLE":               EvmCoinTye,
		"OKB":                  EvmCoinTye,
		"OPTIMISM":             EvmCoinTye,
		"FIL-EVM":              EvmCoinTye,
		"FEVM":                 EvmCoinTye,
		"ETH-LINEA":            EvmCoinTye,
		"BASE":                 EvmCoinTye,
		"OKB-X1":               EvmCoinTye,
		"OKB-X1-ETH":           EvmCoinTye,
		"OKB-X1-USDT":          EvmCoinTye,
		"OKB-X1-USDC":          EvmCoinTye,
		"POLY-USDC-3359":       EvmCoinTye,
		"USDC-OPTIMISM-FF85":   EvmCoinTye,
		"USDC-ARBITRUM-NATIVE": EvmCoinTye,
		"USDC-BASE":            EvmCoinTye,
		"ZKSYNC2":              EvmCoinTye,
		"CORE":                 EvmCoinTye,
		"BERA":                 EvmCoinTye,
		"ARBITRUM":             EvmCoinTye,
		"XLAYER":               EvmCoinTye,
		"AVAXC":                EvmCoinTye,
		"POLYGON":              EvmCoinTye,
		"UNICHAIN":             EvmCoinTye,
		"CFX_EVM":              EvmCoinTye,
		"BSC":                  EvmCoinTye,
		"STORY":                EvmCoinTye,
		"ETH_LINEA":            EvmCoinTye,
		"MERLIN_BTC":           EvmCoinTye,
		"CHZ":                  EvmCoinTye,
		"RONIN":                EvmCoinTye,
		"KAIA":                 EvmCoinTye,
		"ACE":                  EvmCoinTye,
		"MOONBEAM":             EvmCoinTye,
		"METIS":                EvmCoinTye,
		"FLR":                  EvmCoinTye,
		"MOVR":                 EvmCoinTye,
		"SCROLL":               EvmCoinTye,
		"THETA":                EvmCoinTye,
		"SONIC":                EvmCoinTye,
		"LSK":                  EvmCoinTye,
		"CELO":                 EvmCoinTye,
		"G":                    EvmCoinTye,
		"SOPHON":               EvmCoinTye,
		"MERLIN":               EvmCoinTye,
		"OASYS":                EvmCoinTye,
		"ZETA":                 EvmCoinTye,
		"LAT":                  EvmCoinTye,

		// BETH
		"BETH": BethCoinType,

		// TRX
		"USDT-TRC20": TrxCoinType,
		"USDC-TRC":   TrxCoinType,
		"TRX":        TrxCoinType,
		"TRON":       TrxCoinType,

		// ECDSA
		"FIL":            EcdsaCoinType,
		"CFX":            EcdsaCoinType,
		"ELF":            EcdsaCoinType,
		"LUNC":           EcdsaCoinType,
		"OKB-OKC20":      EcdsaCoinType,
		"LTCK-OKC20":     EcdsaCoinType,
		"FILK-OKC20":     EcdsaCoinType,
		"USDC-OKC20":     EcdsaCoinType,
		"SHIBK-KIP20":    EcdsaCoinType,
		"DOTK-OKC20":     EcdsaCoinType,
		"ETCK-KIP20":     EcdsaCoinType,
		"XRPK-KIP20":     EcdsaCoinType,
		"UNIK-OKC20":     EcdsaCoinType,
		"BCHK-KIP20":     EcdsaCoinType,
		"BABYDOGE-KIP20": EcdsaCoinType,
		"LINKK-OKC20":    EcdsaCoinType,
		"TRXK-KIP20":     EcdsaCoinType,
		"OKT":            EcdsaCoinType,
		"USDT-OKC20":     EcdsaCoinType,
		"ETHK-OKC20":     EcdsaCoinType,
		"XRP":            EcdsaCoinType,
		"OKC":            EcdsaCoinType,
		"STX":            EcdsaCoinType,
		"TIA":            EcdsaCoinType,
		"ATOM":           EcdsaCoinType,
		"CRO":            EcdsaCoinType,
		"DORA":           EcdsaCoinType,
		"DYDX":           EcdsaCoinType,
		"INJ":            EcdsaCoinType,
		"TERRA":          EcdsaCoinType,
		"ICX":            EcdsaCoinType,
		"ONE":            EcdsaCoinType,
		"FLOW":           EcdsaCoinType,

		// ED25519
		"SOL":         Ed25519CoinType,
		"USDC-SPL":    Ed25519CoinType,
		"USDT-SPL":    Ed25519CoinType,
		"APTOS":       Ed25519CoinType,
		"APTOS-FA":    Ed25519CoinType,
		"USDT-APTOS":  Ed25519CoinType,
		"USDC-APTOS":  Ed25519CoinType,
		"APT":         Ed25519CoinType,
		"SUI":         Ed25519CoinType,
		"USDC-SUI":    Ed25519CoinType,
		"TONCOIN-NEW": Ed25519CoinType,
		"TON":         Ed25519CoinType,
		"USDT-TON":    Ed25519CoinType,
		"DOT":         Ed25519CoinType,
		"XLM":         Ed25519CoinType,
		"PI":          Ed25519CoinType,
		"STELLAR":     Ed25519CoinType,
		"ADA":         Ed25519CoinType,
		"NEAR":        Ed25519CoinType,
		"HBAR":        Ed25519CoinType,
		"HEDERA":      Ed25519CoinType,
		"ICP":         Ed25519CoinType,
		"ACA":         Ed25519CoinType,
		"CSPR":        Ed25519CoinType,
		"SC":          Ed25519CoinType,
		"IOTA":        Ed25519CoinType,
		"KSM":         Ed25519CoinType,
		"TEZOS":       Ed25519CoinType,
		"KDA":         Ed25519CoinType,
		"EGLD":        Ed25519CoinType,
		"ENJ":         Ed25519CoinType,
		"ALGO":        Ed25519CoinType,
		"ASTR":        Ed25519CoinType,
		"IOST":        Ed25519CoinType,

		// ALGO
		"USDT-ALGO": AlgoCoinType,

		// STARKNET
		"STARKNET-ETH": StarkCoinType,
		"STARKNET":     StarkCoinType,

		// EOS
		"EOS":    EOSCoinType,
		"A":      EOSCoinType,
		"Vaulta": EOSCoinType,
		"VAULTA": EOSCoinType,
		"WAX":    EOSCoinType,
	}

	PorCoinMessageSignatureHeaderMap = map[string]string{
		// UTXO
		"BTC":       BtcMessageSignatureHeader,
		"USDT-OMNI": BtcMessageSignatureHeader,
		"BCHN":      BtcMessageSignatureHeader,
		"BCHA":      BtcMessageSignatureHeader,
		"BSV":       BtcMessageSignatureHeader,
		"BCH":       BtcMessageSignatureHeader,
		"LTC":       LtcMessageSignatureHeader,
		"DOGE":      DogeMessageSignatureHeader,
		"DASH":      DashMessageSignatureHeader,
		"BTG":       BtgMessageSignatureHeader,
		"BCD":       BcdMessageSignatureHeader,
		"DGB":       DgbMessageSignatureHeader,
		"QTUM":      QtumMessageSignatureHeader,
		"RVN":       RvnMessageSignatureHeader,
		"ZEC":       ZecMessageSignatureHeader,

		// ETH
		"ETH":                  EthMessageSignatureHeader,
		"ETH-ARBITRUM":         EthMessageSignatureHeader,
		"ETH-OPTIMISM":         EthMessageSignatureHeader,
		"USDT-ERC20":           EthMessageSignatureHeader,
		"USDT-POLY":            EthMessageSignatureHeader,
		"USDT-AVAXC":           EthMessageSignatureHeader,
		"USDT-ARBITRUM":        EthMessageSignatureHeader,
		"USDT-OPTIMISM":        EthMessageSignatureHeader,
		"USDC":                 EthMessageSignatureHeader,
		"POLY-USDC":            EthMessageSignatureHeader,
		"USDC-AVAXC":           EthMessageSignatureHeader,
		"USDC-ARBITRUM":        EthMessageSignatureHeader,
		"USDC-OPTIMISM":        EthMessageSignatureHeader,
		"ETC":                  EthMessageSignatureHeader,
		"BABYDOGE-BSC":         EthMessageSignatureHeader,
		"SHIB":                 EthMessageSignatureHeader,
		"UNI":                  EthMessageSignatureHeader,
		"LINK":                 EthMessageSignatureHeader,
		"ETHW":                 EthMessageSignatureHeader,
		"BLUR":                 EthMessageSignatureHeader,
		"MATIC":                EthMessageSignatureHeader,
		"PEOPLE":               EthMessageSignatureHeader,
		"OKB":                  EthMessageSignatureHeader,
		"OPTIMISM":             EthMessageSignatureHeader,
		"FIL-EVM":              EthMessageSignatureHeader,
		"FEVM":                 EthMessageSignatureHeader,
		"ETH-LINEA":            EthMessageSignatureHeader,
		"BASE":                 EthMessageSignatureHeader,
		"OKB-X1":               EthMessageSignatureHeader,
		"OKB-X1-ETH":           EthMessageSignatureHeader,
		"OKB-X1-USDT":          EthMessageSignatureHeader,
		"OKB-X1-USDC":          EthMessageSignatureHeader,
		"POLY-USDC-3359":       EthMessageSignatureHeader,
		"USDC-OPTIMISM-FF85":   EthMessageSignatureHeader,
		"USDC-ARBITRUM-NATIVE": EthMessageSignatureHeader,
		"USDC-BASE":            EthMessageSignatureHeader,
		"ZKSYNC2":              EthMessageSignatureHeader,
		"CORE":                 EthMessageSignatureHeader,
		"BERA":                 EthMessageSignatureHeader,
		"XLAYER":               EthMessageSignatureHeader,
		"ARBITRUM":             EthMessageSignatureHeader,
		"POLYGON":              EthMessageSignatureHeader,
		"AVAXC":                EthMessageSignatureHeader,
		"UNICHAIN":             EthMessageSignatureHeader,
		"CFX_EVM":              EthMessageSignatureHeader,
		"BSC":                  EthMessageSignatureHeader,
		"STORY":                EthMessageSignatureHeader,
		"ETH_LINEA":            EthMessageSignatureHeader,
		"MERLIN_BTC":           EthMessageSignatureHeader,
		"CHZ":                  EthMessageSignatureHeader,
		"RONIN":                EthMessageSignatureHeader,
		"KAIA":                 EthMessageSignatureHeader,
		"ACE":                  EthMessageSignatureHeader,
		"MOONBEAM":             EthMessageSignatureHeader,
		"METIS":                EthMessageSignatureHeader,
		"FLR":                  EthMessageSignatureHeader,
		"MOVR":                 EthMessageSignatureHeader,
		"SCROLL":               EthMessageSignatureHeader,
		"THETA":                EthMessageSignatureHeader,
		"SONIC":                EthMessageSignatureHeader,
		"LSK":                  EthMessageSignatureHeader,
		"CELO":                 EthMessageSignatureHeader,
		"G":                    EthMessageSignatureHeader,
		"SOPHON":               EthMessageSignatureHeader,
		"MERLIN":               EthMessageSignatureHeader,
		"OASYS":                EthMessageSignatureHeader,
		"ZETA":                 EthMessageSignatureHeader,
		"LAT":                  EthMessageSignatureHeader,

		// BETH
		"BETH": EthMessageSignatureHeader,

		// TRX
		"USDT-TRC20": TronMessageSignatureHeader,
		"USDC-TRC":   TronMessageSignatureHeader,
		"TRX":        TronMessageSignatureHeader,
		"TRON":       TronMessageSignatureHeader,

		// ECDSA
		"FIL":            OKXMessageSignatureHeader,
		"CFX":            OKXMessageSignatureHeader,
		"ELF":            OKXMessageSignatureHeader,
		"LUNC":           OKXMessageSignatureHeader,
		"OKB-OKC20":      OKXMessageSignatureHeader,
		"LTCK-OKC20":     OKXMessageSignatureHeader,
		"FILK-OKC20":     OKXMessageSignatureHeader,
		"USDC-OKC20":     OKXMessageSignatureHeader,
		"SHIBK-KIP20":    OKXMessageSignatureHeader,
		"DOTK-OKC20":     OKXMessageSignatureHeader,
		"ETCK-KIP20":     OKXMessageSignatureHeader,
		"XRPK-KIP20":     OKXMessageSignatureHeader,
		"UNIK-OKC20":     OKXMessageSignatureHeader,
		"BCHK-KIP20":     OKXMessageSignatureHeader,
		"BABYDOGE-KIP20": OKXMessageSignatureHeader,
		"LINKK-OKC20":    OKXMessageSignatureHeader,
		"TRXK-KIP20":     OKXMessageSignatureHeader,
		"OKT":            OKXMessageSignatureHeader,
		"USDT-OKC20":     OKXMessageSignatureHeader,
		"ETHK-OKC20":     OKXMessageSignatureHeader,
		"XRP":            OKXMessageSignatureHeader,
		"OKC":            OKXMessageSignatureHeader,

		// ED25519
		"SOL":         OKXMessageSignatureHeader,
		"USDC-SPL":    OKXMessageSignatureHeader,
		"USDT-SPL":    OKXMessageSignatureHeader,
		"APTOS":       OKXMessageSignatureHeader,
		"APTOS-FA":    OKXMessageSignatureHeader,
		"USDT-APTOS":  OKXMessageSignatureHeader,
		"USDC-APTOS":  OKXMessageSignatureHeader,
		"SUI":         OKXMessageSignatureHeader,
		"USDC-SUI":    OKXMessageSignatureHeader,
		"TONCOIN-NEW": OKXMessageSignatureHeader,
		"USDT-TON":    OKXMessageSignatureHeader,
		"TON":         OKXMessageSignatureHeader,
		"DOT":         OKXMessageSignatureHeader,
		"XLM":         OKXMessageSignatureHeader,
		"PI":          OKXMessageSignatureHeader,
		"STELLAR":     OKXMessageSignatureHeader,
		"ADA":         OKXMessageSignatureHeader,
		"NEAR":        OKXMessageSignatureHeader,
		"HBAR":        OKXMessageSignatureHeader,
		"HEDERA":      OKXMessageSignatureHeader,
		"SC":          OKXMessageSignatureHeader,
		"ICP":         OKXMessageSignatureHeader,
		"IOTA":        OKXMessageSignatureHeader,
		"ACA":         OKXMessageSignatureHeader,
		"CSPR":        OKXMessageSignatureHeader,
		"KSM":         OKXMessageSignatureHeader,
		"TEZOS":       OKXMessageSignatureHeader,
		"KDA":         OKXMessageSignatureHeader,
		"EGLD":        OKXMessageSignatureHeader,
		"ENJ":         OKXMessageSignatureHeader,
		"STX":         OKXMessageSignatureHeader,
		"ASTR":        OKXMessageSignatureHeader,
		"TIA":         OKXMessageSignatureHeader,
		"ATOM":        OKXMessageSignatureHeader,
		"CRO":         OKXMessageSignatureHeader,
		"DORA":        OKXMessageSignatureHeader,
		"DYDX":        OKXMessageSignatureHeader,
		"INJ":         OKXMessageSignatureHeader,
		"TERRA":       OKXMessageSignatureHeader,
		"IOST":        OKXMessageSignatureHeader,
		"ICX":         OKXMessageSignatureHeader,
		"ONE":         OKXMessageSignatureHeader,
		"FLOW":        OKXMessageSignatureHeader,

		// ALGO
		"USDT-ALGO": OKXMessageSignatureHeader,
		"ALGO":      OKXMessageSignatureHeader,

		// EOS
		"EOS":    OKXMessageSignatureHeader,
		"A":      OKXMessageSignatureHeader,
		"Vaulta": OKXMessageSignatureHeader,
		"VAULTA": OKXMessageSignatureHeader,
		"WAX":    OKXMessageSignatureHeader,
	}

	PorCoinUnitMap = map[string]string{
		// UTXO
		"BTC":       "BTC",
		"USDT-OMNI": "USDT",
		"BCHN":      "BCHN",
		"BCHA":      "BCHA",
		"BSV":       "BSV",
		"LTC":       "LTC",
		"DOGE":      "DOGE",
		"DASH":      "DASH",
		"BTG":       "BTG",
		"BCD":       "BCD",
		"DGB":       "DGB",
		"QTUM":      "QTUM",
		"RVN":       "RVN",
		"ZEC":       "ZEC",

		// ETH
		"ETH":                  "ETH",
		"ETH-ARBITRUM":         "ETH",
		"ETH-OPTIMISM":         "ETH",
		"USDT":                 "USDT",
		"USDT-ERC20":           "USDT",
		"USDT-POLY":            "USDT",
		"USDT-AVAXC":           "USDT",
		"USDT-ARBITRUM":        "USDT",
		"USDT-OPTIMISM":        "USDT",
		"USDT-OKC20":           "USDT",
		"USDC":                 "USDC",
		"POLY-USDC":            "USDC",
		"USDC-AVAXC":           "USDC",
		"USDC-ARBITRUM":        "USDC",
		"USDC-OPTIMISM":        "USDC",
		"ETC":                  "ETC",
		"OKB-OKC20":            "OKB",
		"LTCK-OKC20":           "LTC",
		"FILK-OKC20":           "FIL",
		"USDC-OKC20":           "USDC",
		"SHIBK-KIP20":          "SHIB",
		"DOTK-OKC20":           "DOT",
		"ETCK-KIP20":           "ETC",
		"XRPK-KIP20":           "RIPPLE",
		"UNIK-OKC20":           "UNI",
		"BCHK-KIP20":           "BCH",
		"BABYDOGE-KIP20":       "BABYDOGE",
		"LINKK-OKC20":          "LINK",
		"TRXK-KIP20":           "TRX",
		"BABYDOGE-BSC":         "BABYDOGE",
		"SHIB":                 "SHIB",
		"UNI":                  "UNI",
		"LINK":                 "LINK",
		"ETHW":                 "ETHW",
		"BLUR":                 "BLUR",
		"MATIC":                "MATIC",
		"PEOPLE":               "PEOPLE",
		"OKT":                  "OKT",
		"OKB":                  "OKB",
		"OPTIMISM":             "OPTIMISM",
		"ETH-LINEA":            "ETH",
		"BASE":                 "ETH",
		"OKB-X1":               "OKB",
		"OKB-X1-ETH":           "ETH",
		"OKB-X1-USDT":          "USDT",
		"OKB-X1-USDC":          "USDC",
		"POLY-USDC-3359":       "USDC",
		"USDC-OPTIMISM-FF85":   "USDC",
		"USDC-ARBITRUM-NATIVE": "USDC",
		"USDC-BASE":            "USDC",
		"ZKSYNC2":              "ETH",
		"ETHK-OKC20":           "ETH",
		"STARKNET-ETH":         "ETH",

		// BETH
		"BETH": "BETH",

		// TRX
		"USDT-TRC20": "USDT",
		"USDC-TRC":   "USDC",
		"TRX":        "TRX",

		// ECDSA
		"FIL":  "FIL",
		"CFX":  "CFX",
		"ELF":  "ELF",
		"LUNC": "LUNC",

		// ED25519
		"SOL":         "SOL",
		"USDC-SPL":    "USDC",
		"USDT-SPL":    "USDT",
		"APTOS":       "APTOS",
		"APTOS-FA":    "APTOS",
		"USDT-APTOS":  "USDT",
		"USDC-APTOS":  "USDC",
		"SUI":         "SUI",
		"USDC-SUI":    "USDC",
		"TONCOIN-NEW": "TONCOIN-NEW",
		"USDT-TON":    "USDT",
		"DOT":         "DOT",
		"XLM":         "XLM",
		"PI":          "PI",
		"ADA":         "ADA",
		"NEAR":        "NEAR",
		"HBAR":        "HBAR",

		// EOS
		"EOS":    "EOS",
		"A":      "A",
		"RIPPLE": "RIPPLE",

		// ALGO
		"USDT-ALGO": "USDT",

		// FEVM
		"FIL-EVM": "FIL",
	}

	PorCoinBaseUnitPrecisionMap = map[string]int{
		// UTXO
		"BTC":       8,
		"USDT-OMNI": 6,
		"BCHN":      8,
		"BCHA":      8,
		"BSV":       8,
		"LTC":       8,
		"DOGE":      8,
		"DASH":      8,
		"BTG":       8,
		"BCD":       8,
		"DGB":       8,
		"QTUM":      8,
		"RVN":       8,
		"ZEC":       8,

		// ETH
		"ETH":                  18,
		"ETH-ARBITRUM":         18,
		"ETH-OPTIMISM":         18,
		"USDT":                 6,
		"USDT-ERC20":           6,
		"USDT-POLY":            6,
		"USDT-AVAXC":           6,
		"USDT-ARBITRUM":        6,
		"USDT-OPTIMISM":        6,
		"USDT-OKC20":           18,
		"USDC":                 6,
		"POLY-USDC":            6,
		"USDC-AVAXC":           6,
		"USDC-ARBITRUM":        6,
		"USDC-OPTIMISM":        6,
		"ETC":                  18,
		"OKB-OKC20":            18,
		"LTCK-OKC20":           18,
		"FILK-OKC20":           18,
		"USDC-OKC20":           18,
		"SHIBK-KIP20":          18,
		"DOTK-OKC20":           18,
		"ETCK-KIP20":           18,
		"XRPK-KIP20":           18,
		"UNIK-OKC20":           18,
		"BCHK-KIP20":           18,
		"BABYDOGE-KIP20":       18,
		"LINKK-OKC20":          18,
		"TRXK-KIP20":           18,
		"BABYDOGE-BSC":         18,
		"SHIB":                 18,
		"UNI":                  18,
		"LINK":                 18,
		"ETHW":                 18,
		"BLUR":                 18,
		"MATIC":                18,
		"PEOPLE":               18,
		"OKT":                  18,
		"OKB":                  18,
		"OPTIMISM":             18,
		"ETH-LINEA":            18,
		"BASE":                 18,
		"OKB-X1":               18,
		"OKB-X1-ETH":           18,
		"OKB-X1-USDT":          6,
		"OKB-X1-USDC":          6,
		"POLY-USDC-3359":       6,
		"USDC-OPTIMISM-FF85":   6,
		"USDC-ARBITRUM-NATIVE": 6,
		"USDC-BASE":            6,
		"ZKSYNC2":              18,
		"STARKNET-ETH":         18,

		// BETH
		"BETH": 18,

		// TRX
		"USDT-TRC20": 6,
		"USDC-TRC":   6,
		"TRX":        6,

		// ECDSA
		"FIL":  18,
		"CFX":  18,
		"ELF":  8,
		"LUNC": 6,

		// ED25519
		"SOL":         9,
		"USDC-SPL":    6,
		"USDT-SPL":    6,
		"APTOS":       8,
		"APTOS-FA":    8,
		"USDT-APTOS":  6,
		"USDC-APTOS":  6,
		"SUI":         9,
		"USDC-SUI":    6,
		"TONCOIN-NEW": 9,
		"USDT-TON":    6,
		"DOT":         10,

		// EOS
		"EOS":    4,
		"A":      4,
		"RIPPLE": 6,

		// ALGO
		"USDT-ALGO": 6,

		// FEVM
		"FIL-EVM": 18,
	}

	CheckBalanceCoinBlackList = map[string]bool{
		"DASH": true,
		"DOGE": true,
		"BCHN": true,

		"TRX":      true,
		"USDC-TRC": true,
		"BETH":     true,
		"ETC":      true,

		"FIL":  true,
		"CFX":  true,
		"ELF":  true,
		"LUNC": true,

		"SOL":         true,
		"USDC-SPL":    true,
		"APTOS":       true,
		"TONCOIN-NEW": true,
		"DOT":         true,
		"NEAR":        true,
		"HBAR":        true,

		"RIPPLE": true,

		"USDT-ALGO": true,
		"FIL-EVM":   true,
		"ETH-LINEA": true,
		"BASE":      true,

		"OKB-X1":      true,
		"OKB-X1-ETH":  true,
		"OKB-X1-USDT": true,
		"OKB-X1-USDC": true,
	}

	VerifyAddressCoinBlackList = map[string]bool{
		"EOS":       true,
		"A":         true,
		"RIPPLE":    true,
		"USDT-ALGO": true,
	}
)

func IsCheckBalanceBannedCoin(coin string) bool {
	return CheckBalanceCoinBlackList[coin]
}

func IsVerifyAddressBannedCoin(coin string) bool {
	return VerifyAddressCoinBlackList[coin]
}
